### ISSUE TITLE
[Unsolvable] Script doesn't work with Ubuntu 18.04 + Python 3.6

### ISSUE THREAD

**Issue by kalleswe** [LOENS2/pterodactyl_exporter#14]
Service will not start if done as described on the github page:

Apr  9 13:41:07 server1 pterodactyl_exporter[19586]: /usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   PkgResourcesDeprecationWarning,
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]: /usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 2.17.12ubuntu1.1 is an invalid version and will not be supported in a future release
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   PkgResourcesDeprecationWarning,
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]: Traceback (most recent call last):
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   File "/usr/local/bin/pterodactyl_exporter", line 33, in <module>
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:     sys.exit(load_entry_point('pterodactyl-exporter==0.1.2', 'console_scripts', 'pterodactyl_exporter')())
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   File "/usr/local/lib/python3.6/dist-packages/pterodactyl_exporter-0.1.2-py3.6.egg/pterodactyl_exporter/pterodactyl_exporter.py", line 29, in main
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   File "/usr/local/lib/python3.6/dist-packages/pterodactyl_exporter-0.1.2-py3.6.egg/pterodactyl_exporter/http_client.py", line 41, in get_server
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:     return _default_decoder.decode(s)
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Apr  9 13:41:07 server1 pterodactyl_exporter[19586]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LOENS2** [comment]
1. First of all: Why didin't you use the correct template for the issue type "bug"? This helps a lot when trying to figure out why my sript wont run under certain circumstances. The correct label for this Issue is "bug" and not "enhancement"!

2. Well, the stacktrace literally tells you what are potentialy your problems:
    * You're using Ubuntu 18.04 (Server?)  ``` 0.18ubuntu0.18.04.1 ``` which isn't officially supported.
    * You're using Python 3.6 ``` /usr/local/lib/python3.6 ``` which is proably to old.

3. You don't provide any further information on how your setup looks like. There is only so much i can interpret from the stacktrace. I can't fix a problem just by guessing.

4. Lastly, if you need help with setting up the scripts with Prometheus and Pterodactyl Panel, then feel free to post a question in the "Discussion" tab. The issues are exclusive to actual issues with the code itself.

I'm sorry for my little rant here, but it is very annoying to get the kinds of issues which are really unclear and I'm unable to solve.

**Comment by LOENS2** [comment]
It seems like you don't actually care whether the software works or not. I'll close this issue now, because you didn't respond so far, you didn't post any useful indormation and you seem to do that on other projects, too. 
This is a negative example of how to post an issue!
