### ISSUE TITLE
Make this an Egg

### ISSUE THREAD

**Issue by scarecr0w12** [LOENS2/pterodactyl_exporter#15]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
I would like to be able to set up an Egg within Pterodactyl itself to create the Exporter and have it manage the Start/stop of the exported

**Describe alternatives you've considered**
running as an independent service as currently is set up.

**Additional context**
Since you can create a Prom setup within Pterodactyl using an egg from the Parker repo, it would be extremely valuable to also have the ability to setup and manage an exporter as well within the system to make everything more streamlined for users.

Egg used for Prometheus
https://github.com/parkervcp/eggs/tree/master/monitoring/prometheus

Preferably, having it created when the Prom egg is used and having them automatically connect would be even better.

**Comment by LOENS2** [comment]
That seems like a very sensible idea. I don't know how I didn't come up with that by myself already. I'll look into that tomorrow. Luckily, I already know how to create eggs, so that shouldn't be too complicated for me.

**Comment by scarecr0w12** [comment]
Thats awesome! Glad to hear its a good idea.

**Comment by LOENS2** [comment]
I added the egg in 2c82376. I didn't include the `Preferably, having it created when the Prom egg is used and having them automatically connect would be even better.` because that would require setting up a shared mount in the Panel and I figured, that it would be more difficult to do so than manually changing the `prometheus.yml`. If there is a better way to do so please tell me how i can establish a communication between servers. AFAIK the Pterodactyl team blocked it for security reasons. Furthermore as of right now, you're forced to allocate port 9531 to the server, because it's hard coded and therefor can't be changed by Pterodactyl. I'll be fixing that in the future.
