### ISSUE TITLE
Add support for Pelican Panel

### ISSUE THREAD

**Issue by Exos9** [LOENS2/pterodactyl_exporter#42]
**Is your feature request related to a problem?**
The new Pterodactyl fork, Pelican panel, could really use this project

**Describe the solution you'd like**
Maybe a branch that changes the API endpoints (I'm not sure how much work would be needed to add Pelican panel support)

**Describe alternatives you've considered**
[This](https://github.com/pelican-dev/panel/discussions/44) issue in Pelican panel already describes a possible (but ressource-heavy) alternative.

**Additional context**
N/A

**Comment by LOENS2** [comment]
I already assumed that such an enhancement request would come up, so I already did my research on that.
What I learned so far:
- There are no API Docs (I could find them despite the fact that they should be integrated in the panel now)
- The API should be backwards compatible according to https://pelican.dev/faq
- It is probably not worth supporting pelican until they're out beta (my free time is very small at the moment)
- Due to the current status of the pelican project I have to assume, that there will be many changes to the API during the ongoing development, which makes it impossible to me to ship a guaranteed working version of the exporter as of right now.

Generally, I would be interested in making this exporter compatible with the pelican panel, but I currently have a lack of information as listed above and that makes a production setup impossible. As soon as the project is at a point where I consider supporting it, I'll start with working on the implementation. I don't know whether that will be a completely new exporter or just a branch on this project, because this depends on the difference in feature set between the APIs. As of right know, I don't even know how to properly test the Pelican version of this exporter, because I haven't tried Pelican yet.

I'll try to engage with the developers through the issue you mentioned, but I can't promise anything at the moment.

**Comment by LOENS2** [comment]
I just tried the exporter with the demo install of pelican and it seems to work the as pterodactyl.
Have you tried using the exporter with the pelican panel so far and did yo succeed in doing so?

**Comment by Exos9** [comment]
As far as I can tell, everything is functional on Pelican as well - excellent news!

After looking a bit further into the Pelican API, it seems all Pterodactyl features will remain unchanged, they will only add new features on top of what's existing. So it seems the exporter will keep working with future versions of Pelican as well. Thanks for your help!
