### ISSUE TITLE
Fetch metrics error

### ISSUE THREAD

**Issue by dftzippo** [LOENS2/pterodactyl_exporter#43]
When I start Pterodactyl Exporter (using the Pterodactyl egg) with the server_list_type variable in admin-all it gives me an error and does not send the metrics, if I use the server_list_type variable in owner it sends me the metrics without errors.

And if I suspend the server that is giving the error at that moment it gives me an error with another server (In theory randomly, although I do not know if those two servers have some specific error or pattern that causes the error.

Console Logs:
Python 3.11.11
:/home/********/config.yml
2024-12-12 11:35:28 | Init successful!
2024-12-12 11:35:53 | An error occurred:
	Fetch metrics for Maryna Bot
2024-12-12 11:36:32 | An error occurred:
	Fetch metrics for Maryna Bot
2024-12-12 11:36:51 | An error occurred:
	Fetch metrics for bot angelo
2024-12-12 11:37:05 | An error occurred:
	Fetch metrics for bot angelo
2024-12-12 11:37:24 | An error occurred:
	Fetch metrics for bot angelo
2024-12-12 11:37:38 | An error occurred:
	Fetch metrics for bot angelo
2024-12-12 11:37:57 | An error occurred:
	Fetch metrics for bot angelo
2024-12-12 11:38:12 | An error occurred:
	Fetch metrics for bot angelo

........

**Desktop (please complete the following information):**
 - Distribution: [Ubuntu]
 - Browser [Brave Desktop]
 - Version [22.04 LTS]
 - Python version [3.11.11]
 - Prometheus version [2.53.3]
 - Pterodactyl Panel version [1.11.10]

**Comment by LOENS2** [comment]
Those errors mean that the API returns a non 200 http response code. This is most likely due to a lack of permission which returns a 401 Unauthorized response code. The server list types "" and "owner" only return the servers on which you must have permissions on. However with admin-all, there is no permissions check, because the exporter just returns all of the servers. This requires the account which you use for the API access to have admin privileges.

You can manually check the api with (replace the domain and the server id according to your server):
```
curl "https://pterodactyl.file.properties/api/client/servers/1a7ce997" \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer apikey' \
  -X GET 
  ```

If the response is non 200, than it is most likely a permissions issue.

**Comment by dftzippo** [comment]
The problem was in my panel which had misconfigured permissions of the folders to cache and for that reason could not get the data from those two servers, after assigning the permissions worked correctly.

Therefore I take it as solved
